import { platformIcons } from './icons';

export const ICONS = {
  ...platformIcons,
  SEARCH: require('./../../assets/icons/search.png'),
  MENU: require('./../../assets/icons/menu.png'),
  BACK: require('./../../assets/icons/back.png'),
  INSTANT: require('./../../assets/icons/instant.png'),
  SCAN: require('./../../assets/icons/scan.png'),
  ALBUM: require('./../../assets/icons/album.png'),
  CAMERA: require('./../../assets/icons/camera.png'),
  SAVE: require('./../../assets/icons/save.png'),
  PHOTOGRAPHY: require('./../../assets/icons/photography.png'),
  PLUS: require('./../../assets/icons/plus.png'),
  CLOSE: require('./../../assets/icons/close.png'),
  ARROWS: require('./../../assets/icons/arrows.png'),
  RIGHT: require('./../../assets/icons/right.png'),
  SAVE_PHOTOS: require('./../../assets/icons/save_photo.png'),
  FAVORITE: require('./../../assets/icons/favorite.png'),
  AGENDA: require('./../../assets/icons/agenda.png'),
  CONTACT: require('./../../assets/icons/contact.png'),
  DETAILS: require('./../../assets/icons/details.png'),
  FEEDBACK: require('./../../assets/icons/feedback.png'),
  MAP: require('./../../assets/icons/map.png'),
  MOBILE: require('./../../assets/icons/mobile.png'),
  SPONSOR: require('./../../assets/icons/sponsor.png'),
  TICKET: require('./../../assets/icons/ticket.png'),
  HELP: require('./../../assets/icons/help.png'),
  BOOKMARK: require('./../../assets/icons/bookmark.png'),
  LIKE: require('./../../assets/icons/like.png'),
  GRID: require('./../../assets/icons/grid.png'),
  HOME: require('./../../assets/icons/home.png'),
};
